# Generated by Django 5.0 on 2023-12-15 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-date_added']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-date_added']},
        ),
    ]
